### ISSUE TITLE
Value of type 'DSTextFieldVM' has no member 'textAlignment'

### ISSUE THREAD

**Issue by tumi91** [imodeveloperlab/dskit#29]
**I can not align the text in the right position**
I'm using the Arabic language in my app and I want to make all the text from right to left but DSTextFieldVM does not support text alignment in the right position 

how i can add a property that enables me to choose the text alignment in the right

<img width="1045" alt="Screen Shot 2022-10-07 at 2 00 34 AM" src="https://user-images.githubusercontent.com/24562731/194439321-7a43c3c7-2fca-41ad-8bad-f7db715d526a.png">

**Comment by imodeveloper** [comment]
Fixed
